### PR TITLE
Create python-package.yml

### PR DESCRIPTION
**Pull request by eacharles**
Added a github action to lint and test code

### CODE REVIEW

**Comment by eacharles** [comment]
Added two simple tests (linting and unit tests) to a github action.

**Comment by sschmidt23** [comment]
The GitHub action looks fine, though I see that four of the tests fail on python3.8 and 3.9, so I do think that we should add those python versions back to the python version matrix of checks once we track that specific bug down (my quick guess is that one of the arrays is a list and not a numpy array in the splines).

Also, I'm guessing you saw, but in RAIL Johann and I (basically copying one of the gcr-catalogs actions as an example) cobbled together a codecov check using the codecov/codecov-action@v1 module, do we want to try adding that as well?
see, e.g. here:
https://github.com/LSSTDESC/RAIL/blob/master/.github/workflows/main.yml

**Comment by eacharles** [comment]
1. Yes to adding python 3.8 and 3.9 at some point.   Should we go ahead and to that as part of this PR?
2. Yes to adding coverage.    

Maybe we should follow the example in RAIL more closely?

**Comment by eacharles** [comment]
Ok, fixed the issues with splines in python >= 3.8.  Up to @sschmidt23 if we merge now, or include coverage testing in this PR.

**Comment by sschmidt23** [comment]
I added in the codecov as we set it up in RAIL/estimation, I think it complains a bit for this initial run as it does not have a base to compare against, but it appears to be working.  Neither Johann or I were anywhere near experts when we set up the RAIL actions, so I don't think that we should necessarily follow RAIL closely.  I'm guessing that there are some areas of the RAIL actions that could be cleaned up, I think as we all experiment with actions we may end up making some updates to qp, RAIL, etc... as we get more experienced.

If you are happy with the codecov report, then I think we can merge this (though like I said, it will be happier on the next PR when it has a base commit to compare against, so it's limited in functionality in this last commit).

**Pull request merged**
