### PR TITLE
Issues/10/update ensemble

### PR DESCRIPTION
**Pull request by eacharles**
Added an Ensemble.update() method to update the parameters of an ensemble.
This is needed for fitting.
For now this rebuilds the distributions.  We can revisit this later and have it update the distribution data.
Need to add unit test for this.

### CODE REVIEW

**Review by sschmidt23 — COMMENTED** [review]
Looks good, functions properly when I update parameters for a couple of example distributions.  But, the two new functions aren't covered in the tests.  Maybe add a quick secondary example dataset and update the values, then test that the update was successful?

**Comment by eacharles** [comment]
Well, i added these lines to `tests/test_ensemble.py`:

```
        pdfs_mod = copy.copy(self.ens_h.dist.pdfs)
        pdfs_mod[:,7] = 0.5*pdfs_mod[:,7]
        self.ens_h.update_objdata(dict(pdfs=pdfs_mod))

```

It doesn't actually check that the values were indeed updated.   B/c the values get re-normalized that is a bit more involved than just checking they got set to `pdfs_mod`

**Comment by sschmidt23** [comment]
I don't see those lines in this PR, did you add them to a branch other than issues/10/update_ensemble?

**Comment by eacharles** [comment]
Ah, just forgot to push them.  They should be there now.


-e

**Comment by sschmidt23** [comment]
Ok, looks good now, they're now marked as covered in the coverage report, and things seem to function, so I'd say you're ok to merge.

**Pull request merged**
