### PR TITLE
Issue/8/piecewise linear quantiles

### PR DESCRIPTION
**Pull request by aimalz**
The `quant_gen._pdf()` is now implemented using the same algorithm as in [the old qp](https://github.com/aimalz/qp), only way faster because of the magic of arrays. It still has some inefficiencies that made debugging easier though -- I'm happy to fix any that others can point out.

@eacharles Is it now okay for me to entirely remove `quant_piecewise_gen()` from [quant_pdf.py](https://github.com/LSSTDESC/qp/blob/issue/8/piecewise-linear-quantiles/qp/quant_pdf.py) (and I guess also references to it in various `__init__`s)?

### CODE REVIEW

**Comment by johannct** [comment]
looks like we need to see what is happening with the tests

**Comment by aimalz** [comment]
@johannct Indeed, I'm looking into it now. Something weird is going on in that this isn't satisfying the definition of quantiles, so I think I may have introduced a bug when trying to be efficient.

**Comment by aimalz** [comment]
I'm not sure how to mark an existing PR as a draft, but this has a science bug (and maybe unit test bugs) so is not actually ready for review. Sorry for the false alarm!

**Comment by aimalz** [comment]
After a long discussion with @johannct, the remaining tasks for this PR are:
- [ ] Add in the normalization (quantile consistency) check
- [ ] Get the unit tests to pass (I think I might need some help with this @johannct @eacharles)
- [ ] Use the local derivative of the CDF to choose (x_lo, x_hi)
- [ ] Add in some user warnings when the provided qmin>0 or qmax<1 for conversion to or reconstruction from quantiles

**Comment by eacharles** [comment]
I'm moved this stuff do a different PR.   I more or less started from what you had here, then reframed it in terms of taylor expansion, where what we want is a 2nd order taylor expansion.   That is pretty trivial using the scipy.interp, as that is just an option that you can pass to the c'tor.   The trickier thing was getting the pdf() right, as that is the derivative of the taylor expansion, so I modified the evaluate_hist() methods to allow you to provide a derivative to get you a ramp across the bin.

**Pull request closed without merging**
