### PR TITLE
Remove astropy requirement

### PR DESCRIPTION
**Pull request by heather999**
Address #71

### CODE REVIEW

**Comment by eacharles** [comment]
Probably something that #desc-co should provide guidance on.

**Review by eacharles — APPROVED** [review]
Looks good.

**Comment by eacharles** [comment]
Hmm. it is still picking up tables-io 0.4 even thought 0.5 is on pypi.  Not sure why.

**Comment by heather999** [comment]
The issue with pandas is fixed, but now there seems to be a problem adding astropy 5.0.1 as part of tables_io. It appears to be the same type of problem.  astropy v5 doesn't support py3.7
https://docs.astropy.org/en/stable/install.html#requirements
I'll open a new PR on tables_io and do the same type of thing.  

```
Installed /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pyarrow-7.0.0-py3.7-linux-x86_64.egg
2022-02-24T15:04:23.1631166Z Searching for pandas<1.4.*
2022-02-24T15:04:23.1631466Z Reading https://pypi.org/simple/pandas/
2022-02-24T15:04:23.7364332Z Downloading https://files.pythonhosted.org/packages/3e/0c/23764c4635dcb0a784a787498d56847b90ebf974e65f4ab4053a5d97b1a5/pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=5cce0c6bbeb266b0e39e35176ee615ce3585233092f685b6a82362523e59e5b4
2022-02-24T15:04:23.8865107Z Best match: pandas 1.3.5
2022-02-24T15:04:23.8866205Z Processing pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
2022-02-24T15:04:23.8870910Z Installing pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl to /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages
2022-02-24T15:04:24.3454129Z Adding pandas 1.3.5 to easy-install.pth file
2022-02-24T15:04:24.3477143Z 
2022-02-24T15:04:24.3477710Z Installed /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pandas-1.3.5-py3.7-linux-x86_64.egg
2022-02-24T15:04:24.3522527Z Searching for h5py
2022-02-24T15:04:24.3522904Z Reading https://pypi.org/simple/h5py/
2022-02-24T15:04:24.5537414Z Downloading https://files.pythonhosted.org/packages/52/eb/be456ac07754a2fd884ba105fcc6ed8d375869988282e18705fa966b8e14/h5py-3.6.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl#sha256=e2b49c48df05e19bb20b400b7ff7dc6f1ee36b84dc717c3771c468b33697b466
2022-02-24T15:04:24.6409557Z Best match: h5py 3.6.0
2022-02-24T15:04:24.6411418Z Processing h5py-3.6.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
2022-02-24T15:04:24.6418714Z Installing h5py-3.6.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl to /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages
2022-02-24T15:04:24.7484481Z Adding h5py 3.6.0 to easy-install.pth file
2022-02-24T15:04:24.7496693Z 
2022-02-24T15:04:24.7498089Z Installed /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/h5py-3.6.0-py3.7-linux-x86_64.egg
2022-02-24T15:04:24.7520040Z Searching for astropy
2022-02-24T15:04:24.7520382Z Reading https://pypi.org/simple/astropy/
2022-02-24T15:04:25.3305867Z Downloading https://files.pythonhosted.org/packages/91/a8/619de6e60fe461e3c7e908ec6fa04333b91249e7877a42485b2df981fdcb/astropy-5.0.1.tar.gz#sha256=6382cde6a205aa0b16a0d5e61c0c0131ebd4f0174d6c73e2964f4bee132a9027
2022-02-24T15:04:25.4367140Z Best match: astropy 5.0.1
2022-02-24T15:04:25.4368066Z Processing astropy-5.0.1.tar.gz
2022-02-24T15:04:26.1050050Z Writing /tmp/easy_install-ief8p19j/astropy-5.0.1/setup.cfg
2022-02-24T15:04:26.1051259Z Running astropy-5.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ief8p19j/astropy-5.0.1/egg-dist-tmp-ahbwyb0g
2022-02-24T15:04:26.2258865Z Traceback (most recent call last):
2022-02-24T15:04:26.2270304Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
2022-02-24T15:04:26.2271087Z     yield saved
2022-02-24T15:04:26.2272387Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
2022-02-24T15:04:26.2272886Z     yield
2022-02-24T15:04:26.2273671Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
2022-02-24T15:04:26.2274220Z     _execfile(setup_script, ns)
2022-02-24T15:04:26.2275014Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
2022-02-24T15:04:26.2275545Z     exec(code, globals, locals)
2022-02-24T15:04:26.2276197Z   File "/tmp/easy_install-ief8p19j/astropy-5.0.1/setup.py", line 66, in <module>
2022-02-24T15:04:26.2276869Z ModuleNotFoundError: No module named 'extension_helpers'
2022-02-24T15:04:26.2277160Z 
2022-02-24T15:04:26.2277410Z During handling of the above exception, another exception occurred:
```

**Comment by eacharles** [comment]
Hmm.  I've heard that pinning version is not recommend b/c it makes it harder to fulfill deps, but this stuff getting broken down the road is pretty frustrating to sort out.

**Comment by heather999** [comment]
I really wouldn't recommend explicit pinning - not at this phase of the the repo where there is actively development going on. What we're experiencing is py3.7 end of life.
Some of this dependency stuff would be handled automatically in the tests if we set up a conda-forge env instead - if you were to do a conda install of astropy, it's going to only grab the astropy that will work with py 3.7.  However, maybe it's also useful to understand that some packages no longer support the versions of python that we are testing against rather than enabling us to ignore that.

**Comment by heather999** [comment]
The good news is that with tables_io 0.6 the py3.7 test completes :) the bad news.. even after installing the env successfully, the py3.8 tests are failing. If I had to guess... perhaps due to the more recent release of numpy?

**Comment by eacharles** [comment]
It’s actually scipy that messes stuff up.   I already have fixed for that, which don’t work in 3.7, some I’m putting in a kludgd to skip the offending tests in 3.7

**Comment by eacharles** [comment]
Okay, this is overtaken by the PR on #72, which included these changes, and also works with the new scipy, except for on 3.7.

**Pull request closed without merging**
